# Copyright (c) 2026 Imperal, Inc., Valentin Scerbacov, and contributors
# Licensed under the AGPL-3.0 License. See LICENSE file for details.
"""v1.6.0 validator rules — I-SKELETON-LLM-ONLY + ctx.cache contract.

Seven new rules added on top of the V1-V16 contract in ``validator.py``:

* ``SKEL-GUARD-1`` — ``ctx.skeleton.get(...)`` called from a function whose
  decorator is not ``@ext.skeleton`` (alert tools generated by ``alert=True``
  inherit skeleton access).
* ``SKEL-GUARD-2`` — ``ctx.skeleton_data`` referenced anywhere (attribute
  removed in v1.6.0).
* ``SKEL-GUARD-3`` — ``ctx.skeleton.update(...)`` referenced anywhere
  (method removed in v1.6.0; kernel is sole writer).
* ``CACHE-MODEL-1`` — ``ctx.cache.set/get`` with a model class name not
  registered via ``<ext>.cache_model`` (static AST check).
* ``CACHE-TTL-1`` — ``ctx.cache.set(..., ttl_seconds=X)`` where ``X`` is a
  literal int outside ``[5, 300]``.
* ``MANIFEST-SKELETON-1`` — Tool name matches ``skeleton_refresh_*`` or
  ``skeleton_alert_*`` but decorator is ``@ext.tool`` (should be
  ``@ext.skeleton``).
* ``SDK-VERSION-1`` — ``imperal.json`` missing ``sdk_version`` or
  ``sdk_version < "1.6.0"`` when the extension uses v1.6.0 features
  (``ctx.cache``, ``@ext.skeleton``, etc.).

These run off AST + manifest JSON so they fire in CI **before** deploy, without
importing the extension module. The runtime ``validate_extension(ext)`` cannot
catch them — AST is the source of truth for "did the author call
``ctx.skeleton_data``?" regardless of whether that branch ever executes.

Design intent: keep this module independent of the existing V1-V16 visitor so
both remain under the 300-line project cap. The CLI wires both together.
"""
from __future__ import annotations

import ast
import json
import os
from dataclasses import dataclass, field
from typing import Iterable

from imperal_sdk.types.contributions import ALLOWED_PANEL_SLOTS
from imperal_sdk.validator import ValidationIssue

# TTL bounds mirror imperal_sdk/cache/client.py (_TTL_MIN / _TTL_MAX).
_TTL_MIN = 5
_TTL_MAX = 300

# Decorator names recognised as skeleton-context functions. Functions
# registered by @ext.skeleton(...) are the primary case; the kernel-generated
# paired skeleton_alert_* tool inherits the same access by convention.
_SKELETON_DECORATORS = {"skeleton"}

# File globs to skip in source scan — venv + compiled + test fixtures.
_SKIP_DIR_NAMES = {
    "venv",
    ".venv",
    "__pycache__",
    ".git",
    "node_modules",
    "dist",
    "build",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}


@dataclass
class _FunctionContext:
    """Per-function AST bookkeeping used while walking a module."""
    name: str
    decorator_attrs: list[str] = field(default_factory=list)
    is_skeleton_decorated: bool = False


def _decorator_attr_name(dec: ast.expr) -> str | None:
    """Extract the trailing attribute name from a decorator AST node.

    ``@ext.tool("x")``          → ``"tool"``
    ``@ext.skeleton("monitors")`` → ``"skeleton"``
    ``@chat.function(...)``     → ``"function"``
    ``@ext.panel("p")``         → ``"panel"``
    ``@my_helper``              → ``None`` (not attribute form).
    """
    target = dec.func if isinstance(dec, ast.Call) else dec
    if isinstance(target, ast.Attribute):
        return target.attr
    return None


def _iter_py_files(root: str) -> Iterable[str]:
    """Yield every .py file under ``root``, skipping virtualenvs + caches."""
    for dirpath, dirnames, filenames in os.walk(root):
        # in-place prune to skip descent into venv/cache trees
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIR_NAMES]
        for fname in filenames:
            if fname.endswith(".py"):
                yield os.path.join(dirpath, fname)


def _parse(path: str) -> ast.Module | None:
    try:
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
    except (OSError, UnicodeDecodeError):
        return None
    try:
        return ast.parse(src, filename=path)
    except SyntaxError:
        return None


def _is_ctx_attr(node: ast.AST, attr: str) -> bool:
    """True iff ``node`` is ``ctx.<attr>`` (Attribute of Name 'ctx')."""
    return (
        isinstance(node, ast.Attribute)
        and node.attr == attr
        and isinstance(node.value, ast.Name)
        and node.value.id == "ctx"
    )


def _is_ctx_skeleton_method(node: ast.AST, method: str) -> bool:
    """True iff ``node`` is the attribute ``ctx.skeleton.<method>``.

    Matches the outer Attribute whose value is ``ctx.skeleton``.
    """
    return (
        isinstance(node, ast.Attribute)
        and node.attr == method
        and _is_ctx_attr(node.value, "skeleton")
    )


def _collect_cache_model_names(trees: dict[str, ast.Module]) -> set[str]:
    """Return the set of names passed to ``@<anything>.cache_model("...")``.

    The design doc pins registration to ``<ext>.cache_model`` where ``<ext>``
    is an ``Extension`` instance. Statically we cannot resolve the receiver
    type, so we accept any decorator whose trailing attribute is
    ``cache_model`` and whose first positional arg is a string literal. This
    matches the documented spelling and is strict enough to catch typos.
    """
    names: set[str] = set()
    for tree in trees.values():
        for node in ast.walk(tree):
            if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for dec in node.decorator_list:
                if not isinstance(dec, ast.Call):
                    continue
                attr = _decorator_attr_name(dec)
                if attr != "cache_model":
                    continue
                if dec.args and isinstance(dec.args[0], ast.Constant) and isinstance(dec.args[0].value, str):
                    names.add(dec.args[0].value)
    return names


def _find_cache_call(node: ast.Call) -> str | None:
    """If ``node`` is ``ctx.cache.set(...)`` or ``ctx.cache.get(...)`` return
    the method name, else ``None``.
    """
    func = node.func
    if (
        isinstance(func, ast.Attribute)
        and func.attr in {"set", "get", "get_or_fetch"}
        and _is_ctx_attr(func.value, "cache")
    ):
        return func.attr
    return None


def _extract_cache_model_arg(call: ast.Call, method: str) -> str | None:
    """Pull the model-name argument out of a ``ctx.cache.<method>(...)`` call.

    For ``ctx.cache.set(key, value, ttl_seconds=60)`` the model is inferred
    from ``type(value)``; we can only check this statically when ``value`` is
    a constructor call like ``InboxSummary(...)``. For ``ctx.cache.get(key,
    InboxSummary)`` the model is the second positional arg (a Name).

    Returns the model class name as a string, or ``None`` if we cannot
    determine it from AST (conservative — skip rather than false-positive).
    """
    if method in {"get", "get_or_fetch"}:
        # ctx.cache.get(key, model)  or  ctx.cache.get_or_fetch(key, fetcher, model=...)
        if len(call.args) >= 2 and isinstance(call.args[1], ast.Name):
            return call.args[1].id
        for kw in call.keywords:
            if kw.arg == "model" and isinstance(kw.value, ast.Name):
                return kw.value.id
        return None
    # ctx.cache.set(key, value, ttl_seconds=...) — value is call.args[1]
    if method == "set" and len(call.args) >= 2:
        val = call.args[1]
        if isinstance(val, ast.Call) and isinstance(val.func, ast.Name):
            return val.func.id
        if isinstance(val, ast.Name):
            return val.id
    return None


def _extract_cache_ttl(call: ast.Call) -> int | None:
    """Return literal ``ttl_seconds=`` int arg if present, else ``None``."""
    for kw in call.keywords:
        if kw.arg == "ttl_seconds" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, int):
            return kw.value.value
    return None


def _uses_v1_6_0_features(trees: dict[str, ast.Module]) -> bool:
    """True iff any scanned file uses a v1.6.0 feature.

    Signals: any ``ctx.cache.*`` reference, any ``@ext.skeleton`` (or
    ``@*.skeleton``) decorator, any ``ctx.skeleton.get`` call. This drives
    ``SDK-VERSION-1`` so extensions still on the v1.5.x contract don't get
    warned about a missing ``sdk_version`` they don't need.
    """
    for tree in trees.values():
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and _is_ctx_attr(node.value, "cache"):
                return True
            if isinstance(node, ast.Call):
                if _find_cache_call(node):
                    return True
                if isinstance(node.func, ast.Attribute) and _is_ctx_skeleton_method(node.func, "get"):
                    return True
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for dec in node.decorator_list:
                    if _decorator_attr_name(dec) == "skeleton":
                        return True
    return False


def _collect_skeleton_tool_targets(trees: dict[str, ast.Module]) -> list[tuple[ast.FunctionDef | ast.AsyncFunctionDef, ast.Call, str, str]]:
    """Find ``@ext.tool("skeleton_refresh_*" | "skeleton_alert_*")`` targets.

    Returns (func_node, decorator_call, tool_name, file_path) tuples. Each
    one triggers MANIFEST-SKELETON-1.
    """
    hits = []
    for path, tree in trees.items():
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for dec in node.decorator_list:
                if not isinstance(dec, ast.Call):
                    continue
                if _decorator_attr_name(dec) != "tool":
                    continue
                if not dec.args or not isinstance(dec.args[0], ast.Constant):
                    continue
                tool_name = dec.args[0].value
                if not isinstance(tool_name, str):
                    continue
                if tool_name.startswith("skeleton_refresh_") or tool_name.startswith("skeleton_alert_"):
                    hits.append((node, dec, tool_name, path))
    return hits


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def validate_source_tree(path: str) -> list[ValidationIssue]:
    """Walk ``path`` and apply the AST-based v1.6.0 rules.

    Rules fired from source scan:
    * SKEL-GUARD-1 / 2 / 3
    * CACHE-MODEL-1
    * CACHE-TTL-1
    * MANIFEST-SKELETON-1

    SDK-VERSION-1 lives in :func:`validate_manifest_v1_6_0`.
    """
    issues: list[ValidationIssue] = []
    trees: dict[str, ast.Module] = {}
    for p in _iter_py_files(path):
        t = _parse(p)
        if t is not None:
            trees[p] = t

    registered_models = _collect_cache_model_names(trees)
    # Also collect class names whose definition is decorated by cache_model —
    # the class itself is what gets passed to ctx.cache.set/get, so its Name
    # must round-trip through the registry check.
    registered_class_names: set[str] = set()
    for tree in trees.values():
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for dec in node.decorator_list:
                    if _decorator_attr_name(dec) == "cache_model":
                        registered_class_names.add(node.name)

    for file_path, tree in trees.items():
        issues.extend(_visit_module(file_path, tree, registered_class_names))

    # Manifest rule: tool names that should have been @ext.skeleton.
    for _node, dec, tool_name, file_path in _collect_skeleton_tool_targets(trees):
        section = tool_name.split("_", 2)[-1] if tool_name.startswith("skeleton_refresh_") else tool_name.split("_", 2)[-1]
        issues.append(ValidationIssue(
            rule="MANIFEST-SKELETON-1",
            level="ERROR",
            message=(
                f"Tool {tool_name!r} uses @ext.tool but names a skeleton "
                f"refresh/alert slot. Use @ext.skeleton({section!r}) so the "
                f"kernel auto-wires section metadata."
            ),
            file=_relpath(file_path, path),
            line=getattr(dec, "lineno", 0),
            fix=f"Replace @ext.tool({tool_name!r}) with @ext.skeleton({section!r})",
        ))

    return issues


def _relpath(p: str, root: str) -> str:
    try:
        return os.path.relpath(p, root)
    except ValueError:
        return p


def _visit_module(
    file_path: str,
    tree: ast.Module,
    registered_class_names: set[str],
) -> list[ValidationIssue]:
    """Run SKEL-GUARD-*, CACHE-MODEL-1, CACHE-TTL-1 over one module AST."""
    issues: list[ValidationIssue] = []

    # Walk every function body; track whether it's @*.skeleton-decorated.
    func_stack: list[_FunctionContext] = []

    class V(ast.NodeVisitor):
        def visit_FunctionDef(self, node: ast.FunctionDef) -> None:  # noqa: N802
            self._visit_any_func(node)

        def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:  # noqa: N802
            self._visit_any_func(node)

        def _visit_any_func(self, node):
            attrs = [a for a in (_decorator_attr_name(d) for d in node.decorator_list) if a]
            ctx = _FunctionContext(
                name=node.name,
                decorator_attrs=attrs,
                is_skeleton_decorated="skeleton" in attrs,
            )
            func_stack.append(ctx)
            try:
                self.generic_visit(node)
            finally:
                func_stack.pop()

        def visit_Attribute(self, node: ast.Attribute) -> None:  # noqa: N802
            # SKEL-GUARD-2: ctx.skeleton_data anywhere.
            if _is_ctx_attr(node, "skeleton_data"):
                issues.append(ValidationIssue(
                    rule="SKEL-GUARD-2",
                    level="ERROR",
                    message="ctx.skeleton_data was removed in v1.6.0.",
                    file=file_path,
                    line=node.lineno,
                    fix="Call `await ctx.skeleton.get(section)` from a @ext.skeleton tool instead.",
                ))
            self.generic_visit(node)

        def _check_panel_slot(self, node: ast.Call) -> None:
            """PANEL-SLOT-1 — flag @ext.panel(slot=<unknown literal>)."""
            func = node.func
            if not (isinstance(func, ast.Attribute) and func.attr == "panel"):
                return
            for kw in node.keywords:
                if kw.arg == "slot" and isinstance(kw.value, ast.Constant):
                    val = kw.value.value
                    if isinstance(val, str) and val not in ALLOWED_PANEL_SLOTS:
                        issues.append(ValidationIssue(
                            rule="PANEL-SLOT-1",
                            level="ERROR",
                            message=(
                                f"@ext.panel(..., slot={val!r}) is not a valid slot. "
                                f"Must be one of {sorted(ALLOWED_PANEL_SLOTS)}. "
                                "Note: 'main' was removed in SDK 3.4.0; use 'center' instead."
                            ),
                            file=file_path,
                            line=node.lineno,
                            fix="Replace slot=... with slot='center'",
                        ))
                    return

        def visit_Call(self, node: ast.Call) -> None:  # noqa: N802
            self._check_panel_slot(node)
            func = node.func

            # SKEL-GUARD-3: ctx.skeleton.update(...)
            if _is_ctx_skeleton_method(func, "update"):
                issues.append(ValidationIssue(
                    rule="SKEL-GUARD-3",
                    level="ERROR",
                    message="ctx.skeleton.update() was removed in v1.6.0; kernel is sole writer.",
                    file=file_path,
                    line=node.lineno,
                    fix="Return the refresh payload from a @ext.skeleton tool; kernel persists it.",
                ))

            # SKEL-GUARD-1: ctx.skeleton.get(...) outside @ext.skeleton scope.
            if _is_ctx_skeleton_method(func, "get"):
                if not (func_stack and func_stack[-1].is_skeleton_decorated):
                    enclosing = func_stack[-1].name if func_stack else "<module>"
                    issues.append(ValidationIssue(
                        rule="SKEL-GUARD-1",
                        level="ERROR",
                        message=(
                            f"ctx.skeleton.get(...) called from {enclosing!r}, "
                            f"which is not decorated with @ext.skeleton. "
                            f"Skeleton access is LLM-only in v1.6.0."
                        ),
                        file=file_path,
                        line=node.lineno,
                        fix="Move the read into a @ext.skeleton tool, or use ctx.cache / ctx.store.",
                    ))

            # CACHE-MODEL-1 + CACHE-TTL-1
            method = _find_cache_call(node)
            if method:
                model_name = _extract_cache_model_arg(node, method)
                if model_name and registered_class_names and model_name not in registered_class_names:
                    issues.append(ValidationIssue(
                        rule="CACHE-MODEL-1",
                        level="ERROR",
                        message=(
                            f"ctx.cache.{method}(...) references model "
                            f"{model_name!r} which is not registered via "
                            f"@<ext>.cache_model(...). Register it or use a "
                            f"known class."
                        ),
                        file=file_path,
                        line=node.lineno,
                        fix=f"Add `@ext.cache_model(\"{model_name.lower()}\") class {model_name}(BaseModel): ...`",
                    ))
                if method == "set":
                    ttl = _extract_cache_ttl(node)
                    if ttl is not None and (ttl < _TTL_MIN or ttl > _TTL_MAX):
                        issues.append(ValidationIssue(
                            rule="CACHE-TTL-1",
                            level="ERROR",
                            message=(
                                f"ctx.cache.set(..., ttl_seconds={ttl}) is "
                                f"outside [{_TTL_MIN}, {_TTL_MAX}]."
                            ),
                            file=file_path,
                            line=node.lineno,
                            fix=f"Clamp ttl_seconds to [{_TTL_MIN}, {_TTL_MAX}].",
                        ))

            self.generic_visit(node)

    V().visit(tree)
    return issues


def validate_manifest_v1_6_0(manifest: dict, source_path: str | None = None) -> list[ValidationIssue]:
    """Apply SDK-VERSION-1 against a parsed ``imperal.json``.

    * Warn if the extension uses v1.6.0 features (detected by scanning the
      source tree at ``source_path``) and the manifest is missing
      ``sdk_version`` or has ``sdk_version < "1.6.0"``.
    * Warn unconditionally if the manifest omits ``sdk_version`` — but tagged
      ``INFO`` instead of ``WARN`` when no v1.6.0 features are detected, so
      the noise floor stays low for pre-1.6 extensions.
    """
    uses_v16 = False
    if source_path and os.path.isdir(source_path):
        trees: dict[str, ast.Module] = {}
        for p in _iter_py_files(source_path):
            t = _parse(p)
            if t is not None:
                trees[p] = t
        uses_v16 = _uses_v1_6_0_features(trees)

    sdk_version = manifest.get("sdk_version")
    issues: list[ValidationIssue] = []
    if sdk_version is None:
        issues.append(ValidationIssue(
            rule="SDK-VERSION-1",
            level="WARN" if uses_v16 else "INFO",
            message=(
                "imperal.json missing 'sdk_version'. "
                + ("Extension uses v1.6.0 features; declare `\"sdk_version\": \"1.6.0\"`." if uses_v16
                   else "Declare 'sdk_version' to pin the SDK contract.")
            ),
            file="imperal.json",
            fix='Add `"sdk_version": "1.6.0"` to imperal.json.',
        ))
    else:
        if _version_lt(str(sdk_version), "1.6.0") and uses_v16:
            issues.append(ValidationIssue(
                rule="SDK-VERSION-1",
                level="WARN",
                message=(
                    f"imperal.json declares sdk_version={sdk_version!r} but "
                    f"the extension uses v1.6.0 features (ctx.cache or "
                    f"@ext.skeleton)."
                ),
                file="imperal.json",
                fix='Bump `"sdk_version"` to `"1.6.0"` in imperal.json.',
            ))
    return issues


def _version_lt(a: str, b: str) -> bool:
    """True iff semver string ``a`` is less than ``b``. Non-strict parse."""
    def parts(s: str) -> tuple[int, ...]:
        head = s.split("-", 1)[0]  # strip pre-release
        return tuple(int(x) for x in head.split(".") if x.isdigit())
    try:
        return parts(a) < parts(b)
    except Exception:
        return False
